alias: EnergyHub - Floor 3 Heat Pump Auto Off
description: Auto-off timer for 3rd floor heat pump plug
triggers:
  - entity_id: switch.chuangmi_212a01_ea40_switch
    to: "on"
    id: pump_on
    trigger: state
  - entity_id: switch.chuangmi_212a01_ea40_switch
    to: "off"
    id: pump_off
    trigger: state
  - entity_id: input_number.input_number_floor3_heat_pump_timer_hours
    id: timer_changed
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.floor_3_heat_pump_auto_off
    id: timer_finished
    trigger: event
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ trigger.id in ['pump_on', 'timer_changed'] }}
          - condition: state
            entity_id: switch.chuangmi_212a01_ea40_switch
            state: "on"
          - condition: template
            value_template: >
              {{
              states('input_number.input_number_floor3_heat_pump_timer_hours') |
              int(0) > 0 }}
        sequence:
          - target:
              entity_id: timer.floor_3_heat_pump_auto_off
            data:
              duration: >
                {{ '%02d:00:00' %
                (states('input_number.input_number_floor3_heat_pump_timer_hours')
                | int(0)) }}
            action: timer.start
      - conditions:
          - condition: template
            value_template: |
              {{ trigger.id == 'pump_off' }}
        sequence:
          - target:
              entity_id: timer.floor_3_heat_pump_auto_off
            action: timer.cancel
          - target:
              entity_id: input_number.input_number_floor3_heat_pump_timer_hours
            data:
              value: 0
            action: input_number.set_value
      - conditions:
          - condition: template
            value_template: |
              {{ trigger.id == 'timer_finished' }}
        sequence:
          - target:
              entity_id: switch.chuangmi_212a01_ea40_switch
            action: switch.turn_off
          - target:
              entity_id: input_number.input_number_floor3_heat_pump_timer_hours
            data:
              value: 0
            action: input_number.set_value
mode: restart
